targets:
  $default:
    builders:
      getx_csv_translation_generator|getx_csv_translation:
        options:
          # The default value for each is listed.
          csv_path: ./lib/core/translations.csv
          single_quote: true
          localization_name: AppLocalization